In [24]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import IPython.display

        
df = pd.read_excel("filtration.xlsx",sheet_name=["1回目","2回目","3回目"],usecols=(1,2,3,4,5),dtype='float32')
for values in df_mass.values():
    values['θ/V [s m-3]'] = values['θ [s] (濾過時間)']/values['V [m3] (濾液量)']
    display(values)

    θ [s] (濾過時間)  重量 [g]  積算重量 [kg]  V [m3] (濾液量)   θ/V [s m-3]
0           20.0  1480.0       1.48       0.00148  13513.513672
1           40.0  1210.0       2.69       0.00269  14869.888672
2           60.0  1370.0       4.06       0.00406  14778.324219
3           80.0  1390.0       5.45       0.00545  14678.899414
4          100.0  1300.0       6.75       0.00675  14814.814453
5          120.0  1340.0       8.09       0.00809  14833.127930
6          140.0  1410.0       9.50       0.00950  14736.842773
7          160.0  1350.0      10.85       0.01085  14746.543945
8          180.0  1270.0      12.12       0.01212  14851.485352
9          200.0  1300.0      13.42       0.01342  14903.129883
10         220.0  1260.0      14.68       0.01468  14986.375977
11         240.0  1140.0      15.82       0.01582  15170.669922

    θ [s] (濾過時間)  重量 [g]  積算重量 [kg]  V [m3] (濾液量)   θ/V [s m-3]
0           20.0  1120.0       1.12       0.00112  17857.142578
1           40.0  1290.0       2.41       0.00241  16597.509766
2           60.0  1320.0       3.73       0.00373  16085.791016
3           80.0  1390.0       5.12       0.00512  15625.000000
4          100.0  1250.0       6.37       0.00637  15698.586914
5          120.0  1340.0       7.71       0.00771  15564.202148
6          140.0  1220.0       8.93       0.00893  15677.492188
7          160.0  1270.0      10.20       0.01020  15686.274414
8          180.0  1260.0      11.46       0.01146  15706.806641
9          200.0  1090.0      12.55       0.01255  15936.254883
10         220.0   690.0      13.24       0.01324  16616.314453
11         240.0   330.0      13.57       0.01357  17686.072266

    θ [s] (濾過時間)  重量 [g]  積算重量 [kg]  V [m3] (濾液量)   θ/V [s m-3]
0           20.0  1750.0   1.750000       0.00175  11428.571289
1           40.0  1750.0   3.500000       0.00350  11428.571289
2           60.0  1630.0   5.130000       0.00513  11695.906250
3           80.0  1670.0   6.800000       0.00680  11764.706055
4          100.0  1650.0   8.450000       0.00845  11834.320312
5          120.0  1590.0  10.040000       0.01004  11952.191406
6          140.0  1490.0  11.530000       0.01153  12142.238281
7          160.0  1310.0  12.840000       0.01284  12461.059570
8          180.0   970.0  13.810000       0.01381  13034.033203
9          200.0  1020.0  14.830000       0.01483  13486.176758
10         220.0  1110.0  15.940000       0.01594  13801.756836
11         240.0  1120.0  17.059999       0.01706  14067.995117

# 質量

In [35]:
df_mass = pd.read_excel("filtration.xlsx",sheet_name='質量',usecols=(1,2,3,4,5,6,7,8),dtype='float32')

slurry_X = df_mass['wet slurry 総質量 X [g]']
slurry_x = df_mass['スラリービーカー x [g]']
slurry_z = df_mass['dry slurry  z [g]']
cake_X = df_mass['wat cake 総質量 X [g]']
cake_x = df_mass['wet cakeビーカー x [g]']
cake_z = df_mass['dry cake  z [g]']

df_mass['スラリー濃度[%]'] = (slurry_z-slurry_x) / (slurry_X-slurry_x) * 100
df_mass['湿潤比 m'] = (cake_z-cake_x) / (cake_X-cake_x)

df_mass

,wet slurry 総質量 X [g],スラリービーカー x [g],dry slurry z [g],スラリー濃度[%],wat cake 総質量 X [g],wet cakeビーカー x [g],dry cake z [g],湿潤比 m
0,129.42,61.45,62.35,1.324114,114.1593,61.35,78.49,0.324564
1,130.24,61.75,62.66,1.328661,119.2561,61.31,80.23,0.326510
2,129.03,60.48,61.24,1.108680,121.2800,62.59,82.02,0.331062

# 結果

In [107]:
df_result = pd.read_excel('filtration.xlsx',sheet_name='結果',header=(0,1))

X = [df['1回目']['V [m3] (濾液量)'][6::].values.astype(np.float32),
     df['2回目']['V [m3] (濾液量)'][6::].values.astype(np.float32),
     df['3回目']['V [m3] (濾液量)'][1::].values.astype(np.float32)]

Y = [df['1回目']['θ/V [s m-3]'][6::].values.astype(np.float32),
     df['2回目']['θ/V [s m-3]'][6::].values.astype(np.float32),
     df['3回目']['θ/V [s m-3]'][1::].values.astype(np.float32)]

slope = np.zeros(3)
intercept = np.zeros(3)
for i in range(3):
    slope[i],intercept[i] = np.polyfit(X[i],Y[i],1)

df_result.loc[:,'スラリー濃度 w'] = df_mass['スラリー濃度[%]']
df_result.loc[:,'湿潤比 m'] = df_mass['湿潤比 m']
df_result.loc(:,['K']['実験値']) 
# df_result['Vo']['実験値'] = intercept
# df_result

SyntaxError: invalid syntax (1732688113.py, line 18)

  Unnamed: 0_level_0           スラリー濃度 w              湿潤比 m       濾過圧 ΔPf [Pa]  \
  Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1 Unnamed: 3_level_1
0                1回目           1.324114           0.324564            1000000
1                2回目           1.328661           0.326510            1000000
2                3回目           1.108680           0.331062            1000000

          K            Vo       α      Rc      Rm
        実験値 計算値       実験値 計算値 実験値 計算値 実験値 計算値 実験値 計算値
0  0.000015 NaN  0.106927 NaN NaN NaN NaN NaN NaN NaN
1  0.000003 NaN  0.018426 NaN NaN NaN NaN NaN NaN NaN
2  0.000005 NaN  0.027097 NaN NaN NaN NaN NaN NaN NaN